version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-distribution
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      # 업로드된 파일을 영구 저장
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

